### ISSUE TITLE
DF web returns always the same results

### ISSUE THREAD

**Issue by jeanrjc** [mdmparis/defense-finder-web#7]
Hello,

I've tried with different files, and it leads to the same result (apparently corresponding to the first file).

- 1st file (probably ok) : https://defense-finder.mdmparis-lab.com/result/b96fcfd4-47b6-4985-8f48-89dce6ffd33b.Contig_28_703.295.prt
- 2nd file (only 1 short protein) : https://defense-finder.mdmparis-lab.com/result/67c8a06b-a952-46f9-b88b-1436f96d4259.toto.prt
- 3rd file : https://defense-finder.mdmparis-lab.com/result/2c533bba-4d8b-4f1d-9286-04d8916d57db.b_16693.prt

I guess this is not expected :)

**Comment by Alexandre-Herve** [comment]
Thanks for reporting, I'm fixing this right now I'll keep you posted.

**Comment by Alexandre-Herve** [comment]
The issue should be fixed.
